MetaConfigurator/meta-configurator

- frontend/config-assistant/src/components/code-editor/AceEditor.vue
- frontend/config-assistant/src/components/gui-editor/GuiEditorPanelJsonSchema.vue
- frontend/config-assistant/src/components/gui-editor/PropertiesPanel.vue
- frontend/config-assistant/src/components/gui-editor/PropertyMetadata.vue
- frontend/config-assistant/src/components/gui-editor/SchemaInfoOverlay.vue
- frontend/config-assistant/src/components/gui-editor/SchemaInfoPanel.vue
- frontend/config-assistant/src/helpers/propertyTooltipGenerator.ts
- frontend/config-assistant/src/helpers/schema/JsonSchema.ts
- frontend/config-assistant/src/helpers/schema/schemaDescriptor.ts
It can still have some refinement, e.g. the "anyOf", "oneOf" and "allOf" description look weird, but I think for now I should not invest way more time in it.
> 209 improve schema tooltips

- frontend/config-assistant/src/components/gui-editor/ConfigTreeNodeResolver.ts
- frontend/config-assistant/src/data/SettingsSchema.ts
- frontend/config-assistant/src/helpers/schema/schemaPreprocessor.ts
- frontend/config-assistant/src/store/settingsStore.ts
- fix depth not being set to the right value of anyOf/oneOf nodes
- increase default depth because 3 is a bit low
- fix description being copied into the oneOf/anyOf schemas
> Clean up allof anyof

- frontend/config-assistant/src/components/gui-editor/ConfigTreeNodeResolver.ts
- frontend/config-assistant/src/components/gui-editor/PropertiesPanel.vue
- frontend/config-assistant/src/components/gui-editor/PropertyMetadata.vue
- frontend/config-assistant/src/helpers/errorService.ts
- frontend/config-assistant/src/helpers/focusUtils.ts
- frontend/config-assistant/src/helpers/pathHelper.ts
- frontend/config-assistant/src/helpers/schema/JsonSchema.ts
- frontend/config-assistant/src/model/ConfigDataTreeNode.ts
- frontend/config-assistant/src/store/sessionStore.ts
add "add property" button.
Video in whatsapp
> 220 add property

- frontend/config-assistant/src/components/gui-editor/PropertiesPanel.vue
- frontend/config-assistant/src/components/toolbar/TopMenuBar.ts
- frontend/config-assistant/src/components/toolbar/TopToolbar.vue
- frontend/config-assistant/src/components/toolbar/clearFile.ts
- frontend/config-assistant/src/components/toolbar/clearSchema.ts
- frontend/config-assistant/src/components/toolbar/fetchSchemaFromUrl.ts
- frontend/config-assistant/src/components/toolbar/fetchWebSchemas.ts
- frontend/config-assistant/src/components/toolbar/generateSampleFile.ts
- frontend/config-assistant/src/components/toolbar/uploadFile.ts
- frontend/config-assistant/src/components/toolbar/uploadSchema.ts
- frontend/config-assistant/src/constants.ts
- frontend/config-assistant/src/data/SchemaCollection.ts
- frontend/config-assistant/src/model/SchemaOption.ts
Still needs more refactoring but this is at least a start
> Refactor toolbar

- frontend/config-assistant/src/components/gui-editor/PropertiesPanel.vue
- frontend/config-assistant/src/components/gui-editor/PropertyMetadata.vue
- frontend/config-assistant/src/components/toolbar/TopMenuBar.ts
- frontend/config-assistant/src/components/toolbar/TopToolbar.vue
- frontend/config-assistant/src/fontawesome.ts
- frontend/config-assistant/src/helpers/schema/JsonSchema.ts
- frontend/config-assistant/src/helpers/search.ts
- frontend/config-assistant/src/store/sessionStore.ts
Details see whatsapp
Not part of this pull request:
- highlighting the results in ace editor
- "jumping" to a search result -> this will probably automatically happen when Felix implements the "jumping" from code editor to gui editor.
> implement global search

- frontend/config-assistant/src/components/gui-editor/PropertiesPanel.vue
- frontend/config-assistant/src/components/toolbar/TopToolbar.vue
- frontend/config-assistant/src/constants.ts
- frontend/config-assistant/src/helpers/dataToString.ts
- frontend/config-assistant/src/helpers/search.ts
- frontend/config-assistant/src/router/index.ts
- frontend/config-assistant/src/store/sessionStore.ts
> show search results immediately

- frontend/config-assistant/src/components/gui-editor/ConfigTreeNodeResolver.ts
- frontend/config-assistant/src/components/gui-editor/PropertyMetadata.vue
- frontend/config-assistant/src/data/DefaultSchema.ts
- frontend/config-assistant/src/model/ConfigDataTreeNode.ts
> better property names for array elements

- frontend/config-assistant/resources/json-schema/schema.ts
- frontend/config-assistant/resources/json-schema/simplifiedMetaSchema.ts
- frontend/config-assistant/src/components/gui-editor/ConfigTreeNodeResolver.ts
- frontend/config-assistant/src/components/gui-editor/GuiEditorPanelJsonSchema.vue
- frontend/config-assistant/src/data/DefaultSchema.ts
- frontend/config-assistant/src/helpers/schema/JsonSchema.ts
- frontend/config-assistant/src/helpers/schema/effectiveSchemaCalculator.ts
- frontend/config-assistant/src/helpers/schema/mergeAllOfs.ts
- frontend/config-assistant/src/helpers/schema/schemaPreprocessor.ts
- frontend/config-assistant/src/model/JsonSchemaType.ts
- frontend/config-assistant/src/store/dataStore.ts
- frontend/config-assistant/src/store/sessionStore.ts
Support for
- if then else
- dependent required
- dependent schemas
Remarks:
- if inside allOfs don't work well (only first if is considered). This is not due to my implementation, but due to the mergeAllOf library not supporting merging ifs. In fact, this library basically only supports merging properties and items, which is a pity. It is definitely required that we implement custom resolvers for the merge-all-of (but not necessarily scope of this project)
@Logende I added some comments at which places we could add things for oneOf/anyOf
How to test:
- use Default schema
- set isMarried to true -> spouseName property shows up (if then else)
- define a nickname -> preferredNickname property shows up (dependentSchemas)
- set the city name in the adress -> zipCode becomes required …
> support for data dependent schema keywords

- paper/design.tex
- paper/implementation.tex
- paper/main_paper.tex
Just wrote what was in my head. Not final, not proofread.
> start writing on implementation part

- frontend/config-assistant/src/components/code-editor/AceEditor.vue
We could drag and drop a file from local to our tool now.
> Drag and drop file in ace

- frontend/config-assistant/src/components/gui-editor/PropertiesPanel.vue
- frontend/config-assistant/src/components/gui-editor/PropertyData.vue
- frontend/config-assistant/src/components/gui-editor/PropertyMetadata.vue
- frontend/config-assistant/src/components/gui-editor/properties/BooleanProperty.vue
- frontend/config-assistant/src/components/gui-editor/properties/EnumProperty.vue
- frontend/config-assistant/src/components/gui-editor/properties/IntegerProperty.vue
- frontend/config-assistant/src/components/gui-editor/properties/NumberProperty.vue
- frontend/config-assistant/src/components/gui-editor/properties/OneOfAnyOfSelectionProperty.vue
- frontend/config-assistant/src/components/gui-editor/properties/SimpleArrayProperty.vue
- frontend/config-assistant/src/components/gui-editor/properties/SimpleObjectProperty.vue
- frontend/config-assistant/src/components/gui-editor/properties/StringProperty.vue
- frontend/config-assistant/src/components/gui-editor/resolveCorrespondingComponent.ts
- frontend/config-assistant/src/fontawesome.ts
- frontend/config-assistant/src/helpers/errorService.ts
- frontend/config-assistant/src/helpers/schema/effectiveSchemaCalculator.ts
- frontend/config-assistant/src/helpers/schema/mergeAllOfs.ts
- frontend/config-assistant/src/helpers/schema/schemaDescriptor.ts
- frontend/config-assistant/src/helpers/validationService.ts
- frontend/config-assistant/src/store/sessionStore.ts
more changes then that (see commit messages)
> 286 more clear feedback on invalid data

- frontend/config-assistant/src/components/gui-editor/SchemaInfoPanel.vue
- frontend/config-assistant/src/components/gui-editor/properties/OneOfAnyOfSelectionProperty.vue
- frontend/config-assistant/src/helpers/schema/JsonSchema.ts
- frontend/config-assistant/src/helpers/schema/effectiveSchemaCalculator.ts
- frontend/config-assistant/src/helpers/schema/oneTimeSchemaPreprocessor.ts
- frontend/config-assistant/src/helpers/schema/schemaPreprocessor.ts
- frontend/config-assistant/src/helpers/validationService.ts
- frontend/config-assistant/src/model/JsonSchemaType.ts
- frontend/config-assistant/src/store/dataStore.ts
this will do the following:
- clone the schema, so no data is modified in the schema the user sees
- add titles where it makes sense
- add ids (used for caching the validation functions)
> add one time preprocessing step

- frontend/config-assistant/src/components/gui-editor/PropertiesPanel.vue
Fixes the bugs with the overlay
I also moved the "watches" to the beginning, I think we should put them at the top to see what they are watching
> fix bugs with overlay

- paper/main_paper.tex
- paper/user_study.tex
Sketched a structure of the part User Study.
Question: 
- Do you think we should rename the part?
- Or maybe we could put this part as subsection under some section.(Idk)
- What other points should be mentioned in the part "User Study"?
> [WIP]Paper: UserStudy

- frontend/config-assistant/src/components/gui-editor/PropertiesPanel.vue
- frontend/config-assistant/src/components/gui-editor/PropertyMetadata.vue
- frontend/config-assistant/src/router/index.ts
- frontend/config-assistant/src/store/dataStore.ts
- frontend/config-assistant/src/store/sessionStore.ts
It is now possible to have not a "simple" object at root, but an anyOf / oneOf or a simple type
> allow schemas with anyOf/oneOf at root

- frontend/config-assistant/src/components/gui-editor/PropertiesPanel.vue
remove this code snippet seems to fix the problem
> remove String property from "Add Item"

- frontend/config-assistant/src/components/CombinedEditorComponent.vue
- frontend/config-assistant/src/components/code-editor/AceEditor.vue
- frontend/config-assistant/src/components/toolbar/TopToolbar.vue
- frontend/config-assistant/src/components/toolbar/clearFile.ts
- frontend/config-assistant/src/components/toolbar/downloadFile.ts
- frontend/config-assistant/src/components/toolbar/uploadFile.ts
- frontend/config-assistant/src/components/toolbar/uploadSchema.ts
- frontend/config-assistant/src/store/sessionStore.ts
Fix various bugs, see commit message
> Bugs with session store

- paper/implementation.tex
- paper/main_paper.tex
- paper/user_study.tex
> change table style

- frontend/config-assistant/src/components/gui-editor/PropertiesPanel.vue
- frontend/config-assistant/src/components/gui-editor/PropertyMetadata.vue
- frontend/config-assistant/src/helpers/search.ts
- fix search in recursive schemas
- scroll selected element into view
> improve search in gui editor

- paper/implementation.tex
- paper/main_paper.tex
> shorten abstract

- paper/related-work.tex
Update the evaluation part of the paper
> improve schema language eval

- paper/main_paper.tex
- paper/user_study.tex
not yet final/I'm not yet fully happy with it yet, but this is the current status of the conclusion
> conclusion progress

- paper/appendix.tex
- paper/discussion.tex
- paper/implementation.tex
- paper/literature.bib
- paper/main_paper.pdf
- paper/main_paper.tex
- paper/related-work.tex
work on implementation
I also ran half of it through grammarly
> improve implementation part

- paper/literature.bib
small update about reference
- make note date consistent
- delete unused references
> reference formatting

- frontend/config-assistant/resources/json-schema/simplifiedMetaSchema.ts
In the paper I wrote that we added descriptions to the meta schema, but this was only done exemplary yet. here is the rest
> update meta schema: add descriptions

- paper/appendix.tex
- paper/design.tex
- paper/literature.bib
- paper/main_paper.tex
- paper/related-work.tex
- paper/user_study.tex
What's changed:
- several grammar errors 
- add strenda and enzyme schema citations
> Paper Check

- frontend/config-assistant/src/components/code-editor/AceEditor.vue
- frontend/config-assistant/src/store/settingsStore.ts
- increase default value of maximum depth
- fix font size no response
> Fix small Issues in tool

- meta_configurator/src/components/gui-editor/properties/AnyOfSelectionProperty.vue
- meta_configurator/src/components/gui-editor/properties/OneOfSelectionProperty.vue
Expand after you selected a oneOf / anyOf
could be nice for the presentation
Pretty simple solution
> auto expand one of / any of selection

- meta_configurator/src/utility/validationService.ts
This makes it so we could show schemas from schema store in our presentation
> use the correct version of AJV in validation service depending on schena draft

- meta_configurator/src/components/CombinedEditorComponent.vue
- meta_configurator/src/components/gui-editor/PropertiesPanel.vue
- meta_configurator/src/components/gui-editor/PropertyMetadata.vue
- meta_configurator/src/components/gui-editor/configTreeNodeResolver.ts
- meta_configurator/src/components/gui-editor/properties/AnyOfSelectionProperty.vue
- meta_configurator/src/components/gui-editor/properties/EnumProperty.vue
- meta_configurator/src/components/gui-editor/properties/OneOfSelectionProperty.vue
- meta_configurator/src/components/gui-editor/resolveCorrespondingComponent.ts
- meta_configurator/src/model/oneOfAnyOfSelectionOption.ts
- meta_configurator/src/schema/schemaPreprocessor.ts
- meta_configurator/src/schema/schemaUtils.ts
- meta_configurator/src/store/sessionStore.ts
- meta_configurator/src/store/userSchemaSelectionStore.ts
- meta_configurator/src/utility/dataToString.ts
- meta_configurator/src/utility/readFileContent.ts
I reworked how type unions work and with that the any type now works property (no more interpreting a string as an array!)
One part of this is a bit "quick and dirty" and maybe you have an idea how to make it better
Also no unit tests yet
> improve type unions, make any type work

- meta_configurator/package-lock.json
- meta_configurator/package.json
- meta_configurator/src/components/panels/code-editor/AceEditor.vue
- meta_configurator/src/components/panels/shared-components/aceUtils.ts
- meta_configurator/src/components/toolbar/downloadFile.ts
- meta_configurator/src/dataformats/dataConverter.ts
- meta_configurator/src/dataformats/defaultFormats.ts
- meta_configurator/src/settings/settingsSchema.ts
- meta_configurator/src/settings/settingsTypes.ts
basic support added.
Still missing: PathIndexLinkXml to synchronize the selection in the text editor with other views
> add basic support for XML file format

- meta_configurator/src/components/CombinedEditorComponent.vue
- meta_configurator/src/components/dialogs/FetchedSchemasSelectionDialog.vue
- meta_configurator/src/components/dialogs/UrlInputDialog.vue
- meta_configurator/src/components/toolbar/ModeSelector.vue
- meta_configurator/src/components/toolbar/SearchBar.vue
- meta_configurator/src/components/toolbar/Toolbar.vue
- meta_configurator/src/components/toolbar/TopToolbar.vue
- meta_configurator/src/components/toolbar/TopToolbarMenuButtons.vue
- meta_configurator/src/components/toolbar/menuItems.ts
creating PR already now to run automated CI/CD tests for refactoring.
Will next fix the issue with toolbar if width of page is not big enough.
> 716 if width of tab is not big enough for all menubar elements solve it

- documentation_user/examples/configurator_building/configurator_settings.json
this will cause the default settings for these sections to be used
> Remove configuration settings from JSON
